### ISSUE TITLE
Disable console output

### ISSUE THREAD

**Issue by lenhard** [uniba-dsg/BPMNspector#2]
Is there a way to globally disable any console output for BPMNspector? 

The problem I have is that [INFO] messages from BPMspector, which I am not really interested in, clutter my console. How can I get rid of this? If there is no option yet, please consider this as a feature request :)

**Comment by philippneugebauer** [comment]
You can manually disable the logging in the https://github.com/uniba-dsg/BPMNspector/blob/master/src/main/resources/logback.xml by using `<root level="OFF">`, but currently there is no option to disable the logging in the console. The api has the option to disable the logging

**Comment by lenhard** [comment]
I would be very much in favor of a solution that lets me just generate the `BPMNspector.jar` via `gradlew jar`, take that as-is, include it in my build path and then configure the `BPMNspector` instance to shut the hell up. At the moment I just create a `new BPMNspector` and call `validate`.

So how do I do this via the api?  I really do not want to have to modify the source code, because then I have to do this in every future update.

**Comment by philippneugebauer** [comment]
I think, @matthiasgeiger will implement the disable of the logging in a next version. I just proposed this way for a quick fix. I don't know why @matthiasgeiger did not mention the api usage, but I wrote some explanations how to use it here: https://github.com/philippneugebauer/SchematronBPMNValidator

**Comment by lenhard** [comment]
Unfortunately, the method `setLogLevel` is not available for the `BPMNspector` class. But that looks very convenient, I opt for making that available.

**Comment by philippneugebauer** [comment]
Yeah :/, surprisingly only the `SchematronBPMNValidator` class has this method. @matthiasgeiger removed it though, but I don't know why. You need to wait for him.

**Comment by matthiasgeiger** [comment]
I removed it as the commonly used API for BPMNspector and BPELlint does not have this feature - and moreover also SLF4J does not provide an API method to change the loglevel (as can be seen by the usage of ch.qos.logback.classic.Level in your implementation @philippneugebauer). 
I think I will change the default level for the API usage to remove the (mainly) unneccesary INFO statements.
