### ISSUE TITLE
Investigate correctness of ValidationResult.getFilesWithViolations() on Unix based systems

### ISSUE THREAD

**Issue by matthiasgeiger** [uniba-dsg/BPMNspector#3]
Travis fails at an assertion checking the correct size the List<Path> returned by the getFilesWithViolations() method - though it is no problem on my local windows machine.

Currently assertions are commented out - see 4ed41ff8b54058fe2410acbe52a07729d09fb5d7 

Problem might be, that the refchecking is not using the ```Path``` used to load the file but uses the ```getXMLBaseURI()``` method of an JDOM element.

**Comment by philippneugebauer** [comment]
try it on a linux machine to understand the problem. Somewhen there are crazy differences between linux and windows

**Comment by matthiasgeiger** [comment]
Thats the plan ;-)

However as I currently don't have a Linux partition/VM on my machine I opened this issues as an reminder.

**Comment by matthiasgeiger** [comment]
Fixed in 249921de582b1d56b3554a2d400837bfd4ac0328.
