### ISSUE TITLE
Import location http://localhost:2000/bpel-testpartner?wsdl is not a valid Path

### ISSUE THREAD

**Issue by simonharrer** [uniba-dsg/BPMNspector#5]
Even if the path **is** valid.

**Comment by matthiasgeiger** [comment]
Yes. URLs are currently not resolved correctly only absolute/relative file links are checked.

**Comment by simonharrer** [comment]
A warning would be nice so that no urls are supported.

**Comment by matthiasgeiger** [comment]
:+1:
