### ISSUE TITLE
HTML Report prints valid despite several rule violations

### ISSUE THREAD

**Issue by simonharrer** [uniba-dsg/BPMNspector#7]
![image](https://cloud.githubusercontent.com/assets/375693/10302546/9e5b1900-6c0d-11e5-9958-be20b260189a.png)

Why is there a valid sign next to the checked file?

**Comment by philippneugebauer** [comment]
From my point of view, `#if ($validationResult.getFilesWithViolations().contains($path))` in https://github.com/uniba-dsg/BPMNspector/blob/master/src/main/resources/reporting/ValidationResult.vm (Line 33) does not seem to work properly.

**Comment by matthiasgeiger** [comment]
Might be caused by the usage of relativ paths - will check this later.
