### ISSUE TITLE
ItemDefinition EXT.044

### ISSUE THREAD

**Issue by simonharrer** [uniba-dsg/BPMNspector#8]
4	C:\projects\BPMNspector\..\betsy\src\main\tests\files\bpmn\activities\ServiceTask.bpmn	64	EXT.044	The ItemDefinition of the DataInput of the ServiceTask and the inMessage of the referenced Operation must be equal.

**Comment by matthiasgeiger** [comment]
Caused by mixed usage of prefixed and unprefixed id values (`theID` vs. `tns:theID').
